### PR TITLE
fastq -> fasta

### PR DESCRIPTION
**Pull request by erinyoung**
This PR should fix the issues:
- only one file per sample
  - this appeared to be due to a subworkflow, which I've replaced
- not all files getting to multiqc
  - there still isn't an easy way to determine if samples have passed or failed
- mapped reads form a consensus, unmapped reads are converted to fasta files
  - still being tested: using blast on these fasta files
- spades for unmapped reads was tested. If all unmapped reads were from amplicons... this would be fine, but there are a lot of non-amplicon reads.

No tests have been set up for this workflow.

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/vectordetectivetest/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, also make a PR on the nf-core/vectordetectivetest _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by erinyoung** [comment]
I think I have added in blast functionality. It takes a long time for the sample files, mostly because there are so many unmapped reads.

I think this is now ready for your review. 

Although I think this is functional, 
- there are now some subworkflows and modules that are no longer used and should be deleted
- there are still TODO messages left to fix
- there are still tests to set up
- there still needs to be a good final report indicating if a sample passed/failed the workflow

**Comment by saarman** [comment]
Thanks Erin!

What do you think about using a subsample of the unmapped reads? That could speed things up considerably!

Norah
________________________________

**Comment by erinyoung** [comment]
Subsampling the unmapped reads would be great thing! Did you want to try to add that to this branch or a separate one?

**Comment by saarman** [comment]
I think it would be great to add it to the main branch, since if we over sequence or not, subsampling would not be a problem... right?

Maybe subsample 5000 reads just to be safe?
________________________________

**Comment by erinyoung** [comment]
I'll add in seqkit's sample option https://bioinf.shenwei.me/seqkit/usage/#sample

What do you think would happen if we removed duplicates? (https://bioinf.shenwei.me/seqkit/usage/#rmdup)

**Comment by saarman** [comment]
That would make sense to me, but I've never worked with exactly this type of data... worth a try?

On Apr 17, 2024, at 5:10 PM, Young ***@***.***> wrote:

﻿

I'll add in seqkit's sample option https://bioinf.shenwei.me/seqkit/usage/#sample

What do you think would happen if we removed duplicates? (https://bioinf.shenwei.me/seqkit/usage/#rmdup)

**Comment by erinyoung** [comment]
I've added in a subsampling step. Right now it only maps the unmapped reads.

**Review by emcal23 — APPROVED** [review]
approving request

**Review by emcal23 — APPROVED** [review]
trying to pull on chpc

**Review by emcal23 — APPROVED** [review]
trying to merge

**Pull request merged**
